name:                mergesort
version:             0.1.0.0
github:              "githubuser/mergesort"
license:             BSD3
author:              "Nitin"
maintainer:          "example@example.com"
copyright:           "2021 Nitin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mergesort#readme>

dependencies:
- base >= 4.7 && < 5
- liquid-base >= 4.15.0.0
- liquidhaskell >= 0.8.10.1

library:
  source-dirs: src

executables:
  mergesort-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mergesort

tests:
  mergesort-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mergesort
